### ISSUE TITLE
多帧动画运动曲线 animation-timing-function 表现和 w3c 不一致问题

### ISSUE THREAD

**Issue by luwuer** [quickappcn/issues#78]
### 关联信息
- 快应用版本： 预览版 1060
- IDE版本：1.6.0
- 手机型号：小米6

### 问题描述
关键帧大于2时，快应用动画曲线实现与预期（w3c）不同。

预期结果：`animation-timing-function`作用于单个关键帧周期，每个关键帧周期都有相同的运动曲线,[MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/animation-timing-function)

实际效果：`animation-timing-function`应用在了所有关键帧周期，整个动画只有一条曲线，导致非`linear`时每个关键帧周期的运动曲线不一致

### 复现步骤
对比该CSS动画在快应用和浏览器上的差异
```css
.animate-item-scale {
  animation-duration: 1s;
  animation-timing-function: ease-in-out;
  animation-name: animateScale;
}

@keyframes animateScale {
  0% {
    transform: scale(1);
  }
  50% {
    transform: scale(2);
  }
  100% {
    transform: scale(1);
  }
}
```

### 联系方式
微信：15575861294
